edit pr template
UTM-Hacklab/VIAplanner pull request #366
Opened 2023-06-16 04:35 UTC by huonggiangbui

## feat/[name]

Fixes: #

- [ ] Has the code been formatted?
- [ ] Have dependencies/packages been added/removed?
      If so, please list them.

### Changes

List out all the changes, and then explain the changes made at a higher level

Test if code climate plugin works, by making small changes to PR template

2023-06-16 04:38 UTC, logonoff requested changes

2023-06-16 04:38 UTC, logonoff commented on .github/pull_request_template.md
> +Please include images/screenshots if applicable.
could also ask for a screen recording

2023-06-16 04:41 UTC, logonoff requested changes

2023-06-16 04:41 UTC, logonoff commented on .github/pull_request_template.md
> +Please include images/screenshots if applicable.
if you were intending for this to be on it a newline when rendered in md, it isn't

2025-02-22 18:25 UTC, logonoff approved these changes

2025-02-22 18:28 UTC, ggggg approved these changes

2025-02-22 18:28 UTC, merged