fixed typo in readme file
UTM-Hacklab/VIAplanner pull request #373
Opened 2023-12-29 01:22 UTC by Qwerty-Shorty

fix #372

 Typo in readme file

Fixes: #372

- [x] Has the code been formatted?
- [] Have dependencies/packages been added/removed?
      If so, please list them.

### Changes
"cd VIAplanner" --> "cd via-timetable"

2023-12-30 06:55 UTC, ggggg requested changes

2023-12-30 06:55 UTC, ggggg commented on README.md
>  git clone https://github.com/VIAplanner/VIAplanner.git
I think this link is wrong as well

2023-12-31 02:07 UTC, ggggg approved these changes
Lgtm

2024-01-08 14:53 UTC, huonggiangbui approved these changes

2024-01-19 23:41 UTC, merged